# Generated by Django 4.0.4 on 2022-05-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
