# Generated by Django 4.0.4 on 2022-05-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comm',
        ),
    ]
